config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resource :like, module: :posts
  end

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :likes
  validates :user_id, presence: true

  def likes?(post)
    post.likes.where(user_id: id).any?
  end

  def avatar_url
    hash = Digest::MD5.hexdigest(email)
     "https://secure.gravatar.com/avatar/#{hash}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @post.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def destroy
    @post.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LikingPosts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>

    <% if notice %><div class="alert alert-success" role="alert"><%= notice %></div><% end %>
    <% if alert %><div class="alert alert-warning" role="alert"><%= alert %></div><% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-light bg-faded">
  <div class="container">
    <div class="nav navbar-nav">
      <%= link_to 'Blog', root_path, class: 'navbar-brand' %>
      <div class="float-xs-right">
      <% if user_signed_in? %>
        <%= link_to 'Account', edit_user_registration_path, class: 'btn btn-secondary' %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-secondary' %>
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-secondary' %>
        <%= link_to 'Login', new_user_session_path, class: 'btn btn-secondary' %>
      <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/posts/_likes.html.erb
<% if user_signed_in? && current_user.likes?(post) %>
  <%= link_to 'Unlike', post_like_path(post), method: :delete, remote: true %>
<% else %>
  <%= link_to 'Like', post_like_path(post), method: :post, remote: true %>
<% end %>

<%= post.likes.count %>

<%= post.likes.each do |like| %>
  <%= image_tag like.user.avatar_url, alt: like.user.email, width: 20 %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1 class="page-header">Listing posts</h1>

<% @posts.each do |post| %>
  <h3><%= link_to post.title, post %></h3>
  <div><%= simple_format post.body %></div>
  <p id="post_<%= post.id %>_likes"><%= render partial: 'likes', locals: {post: post} %></p>
  <hr />
<% end %>

<%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>

app/views/posts/likes/create.js.erb
$("#post_<%= @post.id %>_likes").html("<%= j render partial: 'posts/likes', locals: {post: @post} %>");

app/views/posts/likes/destroy.js.erb
$('#post_<%= @post.id %>_likes').html("<%= j render partial: 'posts/likes', locals: {post: @post} %>");

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1 class="page-header"><%= @post.title %></h1>

<hr>

<p>
  <%= @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<div id="post_<%= @post.id %>_likes">
  <%= render partial: 'likes', locals: {post: @post} %>
</div>